name: Solar System Workflow

on: 
  workflow_dispatch:
  push:
    branches:
      - main
      - 'feature/*'
env:
    MONGO_URI: mongodb+srv://supercluster.d83jj.mongodb.net/superData
    MONGO_USERNAME: superuser
    MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}

permissions: 
    contents: read
    packages: write
    
jobs:
    unit-testing:
        name: Unit Testing
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Setup NodeJS Version
          uses: actions/setup-node@v4
          with:
            node-version: 20
    
        - name: Install Dependencies
          run: npm install
    
        - name: Unit Testing
          run: npm test
          
        - name: Archive Test Result
          uses: actions/upload-artifact@v4
          with:
            name: Mocha-Test-Result
            path: test-results.xml
        - name: Cache NPM dependencies
          uses: actions/cache@v4
          with:
            path: ~/.npm
            key: "${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}"

    docker:
      name: Dockerize
      runs-on: ubuntu-latest

      needs:
        - unit-testing
      steps:
        - name: Install sources
          uses: actions/checkout@v4
      
        - name: Login to GitHub Container Registry
          uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{ github.repository_owner }}
            password: ${{ secrets.GITHUB_TOKEN }}  

        - name: Login to DockerHub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USER }}
            password: ${{ secrets.DOCKERHUB_PASSWORD }}  

            
        -
          name: Set up QEMU
          uses: docker/setup-qemu-action@v3
        # -
        #   name: Set up Docker Buildx
        #   uses: docker/setup-buildx-action@v3
        -
          name: Build for Test
          uses: docker/build-push-action@v6
          with:
            context: .
            push: false
            tags: | 
              ${{ github.repository_owner }}/solar-system:${{ github.sha }}
              solar-system:${{ github.sha }}
              solar-system:latest

           
        - name: image test
          run: |
            docker images
            docker run --name solar-system-app -d \
              -p 3000:3000 \
              -e MONGO_URI=$MONGO_URI \
              -e MONGO_USERNAME=$MONGO_USERNAME \
              -e MONGO_PASSWORD=$MONGO_PASSWORD \
              solar-system:${{ github.sha }}

            echo "see if image returns expected live endpoint"
            wget -q -O - 127.0.0.1:3000/live | grep live
        
        - name: Dockerhub repo push
          uses: docker/build-push-action@v6
          with:
            context: .
            push: true
            tags: | 
              ${{ github.repository_owner }}/solar-system:${{ github.sha }}
              ${{ github.repository_owner }}/solar-system:latest
        
        - name: GHCR repo push
          continue-on-error: true
          uses: docker/build-push-action@v6
          with:
            context: .
            push: true
            tags: | 
              ${{ github.repository_owner }}/solar-system:${{ github.sha }}
              ghcr.io/${{ github.repository_owner }}/solar-system:${{ github.sha }}

    kind:
        name: Install kind and pull to K8s
        runs-on: ubuntu-latest
        needs:
        - docker
        steps:
        - name: install cluster
          uses: helm/kind-action@v1
        - name: Pull image
          run: |
            # wait for DNS and run image
            set +e
            sleep 60
            kubectl -n kube-system get pod
            kubectl run solar --image ghcr.io/${{ github.repository_owner }}/solar-system:${{ github.sha }} \
               --pod-running-timeout 60s \
               --env MONGO_URI=${{ env.MONGO_URI}} \
               --env MONGO_USERNAME=${{ env.MONGO_USERNAME}} \
               --env MONGO_PASSWORD=${{ env.MONGO_PASSWORD}}

            echo "kubectl returned $?"
            sleep 10
            kubectl logs solar
